function check_dependencies()
%CHECK_DEPENDENCIES Report MATLAB release and verify required functions.

    requiredFunctions = { ...
        'ode45', ...
        'optimvar', 'optimproblem', 'fcn2optimexpr', ...
        'lillietest', 'ttest', 'signrank'};
    missingFunctions = requiredFunctions( ...
        cellfun(@(name) isempty(which(name)), requiredFunctions));

    fprintf('MATLAB release: %s\n', version('-release'));
    if ~isempty(missingFunctions)
        error('Dependencies:MissingFunctions', ...
            ['Required MATLAB functions are unavailable: %s. ', ...
             'Install/enable Optimization Toolbox and Statistics and ', ...
             'Machine Learning Toolbox.'], strjoin(missingFunctions, ', '));
    end
    fprintf(['Dependency check passed: MATLAB, Optimization Toolbox, ', ...
        'and Statistics and Machine Learning Toolbox functions found.\n']);
end
